DROP TABLE IF EXISTS accesses;

CREATE TABLE `accesses` (
  `uid` VARCHAR(32) NOT NULL,
  `jti` VARCHAR(32) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`, `jti`)
);